const express = require("express");
const router = express.Router();
const fs = require("fs");
const path = require("path");
const archiver = require("archiver");
const { sequelize } = require("../models");
const { exec } = require('child_process');
const util = require('util');
const execPromise = util.promisify(exec);

// Helper function to escape MySQL string
function mysqlEscape(str) {
  if (str === null || str === undefined) return 'NULL';
  return "'" + String(str).replace(/['\\]/g, '\\$&').replace(/\n/g, '\\n') + "'";
}

// Helper function to format value for SQL
function formatSQLValue(value) {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'number') return value;
  if (typeof value === 'boolean') return value ? 1 : 0;
  if (value instanceof Date) return mysqlEscape(value.toISOString().slice(0, 19).replace('T', ' '));
  if (typeof value === 'object') return mysqlEscape(JSON.stringify(value));
  return mysqlEscape(value);
}

// Generate SQL dump from database
async function generateSQLDump() {
  try {
    console.log("💾 Generating SQL dump...");
    
    // Get database name
    const dbName = process.env.DB_NAME || 'shop_management';
    
    // Get all tables
    const [tables] = await sequelize.query(
      "SELECT table_name FROM information_schema.tables WHERE table_schema = ?",
      { replacements: [dbName] }
    );

    let sql = `-- MySQL dump generated by Shop Management System
-- Database: ${dbName}
-- Generated: ${new Date().toISOString()}
-- ------------------------------------------------------

SET FOREIGN_KEY_CHECKS = 0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

-- ------------------------------------------------------
-- Create database if not exists
-- ------------------------------------------------------
CREATE DATABASE IF NOT EXISTS \`${dbName}\`;
USE \`${dbName}\`;

`;

    // Get create table syntax for each table
    for (const table of tables) {
      const tableName = table.table_name || table.TABLE_NAME;
      console.log(`   📊 Processing table: ${tableName}`);
      
      // Get CREATE TABLE statement
      const [createStmt] = await sequelize.query(`SHOW CREATE TABLE \`${tableName}\``);
      const createSQL = createStmt[0]['Create Table'];
      
      // Add DROP TABLE and CREATE TABLE
      sql += `-- ------------------------------------------------------\n`;
      sql += `-- Table structure for table \`${tableName}\`\n`;
      sql += `-- ------------------------------------------------------\n`;
      sql += `DROP TABLE IF EXISTS \`${tableName}\`;\n`;
      sql += `${createSQL};\n\n`;

      // Get all data from table
      const [rows] = await sequelize.query(`SELECT * FROM \`${tableName}\``);
      
      if (rows.length > 0) {
        sql += `--\n-- Dumping data for table \`${tableName}\`\n--\n`;
        
        // Get column names
        const columns = Object.keys(rows[0]);
        const columnList = columns.map(col => `\`${col}\``).join(', ');
        
        // Insert in batches of 100 rows
        for (let i = 0; i < rows.length; i += 100) {
          const batch = rows.slice(i, i + 100);
          const values = batch.map(row => {
            const rowValues = columns.map(col => formatSQLValue(row[col]));
            return `(${rowValues.join(', ')})`;
          }).join(',\n');
          
          sql += `INSERT INTO \`${tableName}\` (${columnList}) VALUES\n${values};\n\n`;
        }
      }
    }

    // Add footer
    sql += `-- ------------------------------------------------------\n`;
    sql += `-- Set foreign key checks back on\n`;
    sql += `-- ------------------------------------------------------\n`;
    sql += `SET FOREIGN_KEY_CHECKS = 1;\n`;
    sql += `COMMIT;\n\n`;
    sql += `/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;\n`;
    sql += `/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;\n`;
    sql += `/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;\n`;

    console.log(`   ✅ SQL dump generated: ${(sql.length / 1024 / 1024).toFixed(2)} MB`);
    return sql;
    
  } catch (error) {
    console.error("❌ SQL dump generation error:", error);
    throw error;
  }
}

// Alternative: Use mysqldump command line (faster for large databases)
async function generateSQLDumpWithMysqldump() {
  try {
    console.log("💾 Generating SQL dump using mysqldump...");
    
    const dbHost = process.env.DB_HOST || 'localhost';
    const dbPort = process.env.DB_PORT || 3306;
    const dbName = process.env.DB_NAME || 'shop_management';
    const dbUser = process.env.DB_USER || 'root';
    const dbPassword = process.env.DB_PASSWORD || '';
    
    // Build mysqldump command
    let cmd = `mysqldump -h ${dbHost} -P ${dbPort} -u ${dbUser}`;
    
    if (dbPassword) {
      cmd += ` -p${dbPassword}`;
    }
    
    cmd += ` --single-transaction --routines --triggers --events ${dbName}`;
    
    console.log(`   Running: mysqldump command`);
    
    const { stdout, stderr } = await execPromise(cmd, { maxBuffer: 1024 * 1024 * 100 }); // 100MB buffer
    
    if (stderr) {
      console.warn('   mysqldump warnings:', stderr);
    }
    
    console.log(`   ✅ SQL dump generated: ${(stdout.length / 1024 / 1024).toFixed(2)} MB`);
    return stdout;
    
  } catch (error) {
    console.error("❌ mysqldump failed, falling back to manual dump:", error.message);
    // Fall back to manual method if mysqldump is not available
    return await generateSQLDump();
  }
}

// Download backup as SQL file
router.get("/download", async (req, res) => {
  console.log("📦 SQL Backup download started");
  
  const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
  const uploadsDir = path.join(__dirname, "../uploads");
  
  try {
    // Check if client wants SQL only or full backup with uploads
    const format = req.query.format || 'full'; // 'sql' or 'full'
    
    if (format === 'sql') {
      // Return SQL file directly
      console.log("📄 Generating SQL file only...");
      const sql = await generateSQLDump();
      
      res.setHeader('Content-Type', 'application/sql');
      res.setHeader('Content-Disposition', `attachment; filename="database-backup-${timestamp}.sql"`);
      res.setHeader('Content-Length', Buffer.byteLength(sql));
      
      return res.send(sql);
    }
    
    // Full backup with uploads folder (ZIP containing SQL file)
    console.log("📦 Generating full backup with uploads...");
    
    // Create archive
    const archive = archiver("zip", { zlib: { level: 6 } });

    archive.on("error", (err) => {
      console.error("❌ Archive error:", err);
      res.status(500).json({ error: err.message });
    });

    // Set headers
    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', `attachment; filename="full-backup-${timestamp}.zip"`);

    // Pipe to response
    archive.pipe(res);

    // Generate SQL dump
    console.log("💾 Generating SQL dump...");
    const sql = await generateSQLDump();
    archive.append(sql, { name: `database/backup-${timestamp}.sql` });
    console.log("✅ SQL dump added to archive");

    // Add uploads folder
    if (fs.existsSync(uploadsDir)) {
      const files = fs.readdirSync(uploadsDir);
      console.log(`📁 Adding ${files.length} files from uploads`);
      
      files.forEach(file => {
        const filePath = path.join(uploadsDir, file);
        if (fs.statSync(filePath).isFile()) {
          archive.file(filePath, { name: `uploads/${file}` });
        }
      });
    }

    // Add restore instructions
    const restoreInstructions = `# Restore Instructions
# ----------------------

## Option 1: Restore Database Only
1. Open MySQL command line or phpMyAdmin
2. Run: source database/backup-${timestamp}.sql
3. Or import using: mysql -u username -p database_name < backup.sql

## Option 2: Restore Full Backup
1. Extract this ZIP file
2. Import the SQL file using method above
3. Copy uploads folder to your server

## MySQL Command:
mysql -u ${process.env.DB_USER || 'root'} -p ${process.env.DB_NAME || 'shop_management'} < database/backup-${timestamp}.sql

## Created: ${new Date().toISOString()}
`;
    archive.append(restoreInstructions, { name: 'RESTORE_INSTRUCTIONS.txt' });

    // Add metadata
    const metadata = {
      timestamp,
      database: process.env.DB_NAME || 'shop_management',
      fileCount: fs.existsSync(uploadsDir) ? fs.readdirSync(uploadsDir).length : 0,
      version: "2.0",
      createdAt: new Date().toISOString(),
      format: "sql"
    };
    archive.append(JSON.stringify(metadata, null, 2), { name: "metadata.json" });

    // Finalize
    console.log("📦 Finalizing archive...");
    await archive.finalize();
    console.log("✅ Backup complete");

  } catch (error) {
    console.error("❌ Backup failed:", error);
    if (!res.headersSent) {
      res.status(500).json({ error: error.message });
    }
  }
});

// Get SQL dump only (no uploads)
router.get("/sql", async (req, res) => {
  console.log("📄 SQL dump only requested");
  
  const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
  
  try {
    const sql = await generateSQLDump();
    
    res.setHeader('Content-Type', 'application/sql');
    res.setHeader('Content-Disposition', `attachment; filename="database-backup-${timestamp}.sql"`);
    res.setHeader('Content-Length', Buffer.byteLength(sql));
    
    res.send(sql);
    
  } catch (error) {
    console.error("❌ SQL dump failed:", error);
    res.status(500).json({ error: error.message });
  }
});

module.exports = router;